# parameters.yaml specification for FLAM-Seq analysis

experimentName: "test"

experiment:
  rawFastq: ""
  outputDir: "outputDir"
  passFile: "/public-supool/home/niehu/polyA_pipeline_test/MIIAB.ccs.pass.txt"
  barcodeFile: "/public-supool/home/niehu/PAIso-SeqAnalysis/barcode.fa"
  genomeIndexFile: "/public-supool/home/niehu/LFL_lab/database_jxzhang/Sequence_And_Annotation/01.Mus_musculus/01.mm10/01.genome/04.ENSEMBL/pacbio_index/Mus_musculus.mmi"
  juncBed: ""
  annotationGTF: "/public-supool/home/niehu/LFL_lab/database_jxzhang/Sequence_And_Annotation/01.Mus_musculus/01.mm10/01.genome/04.ENSEMBL/Mus_musculus.GRCm38.92.gtf"
  genomeFasta: "/public-supool/home/niehu/LFL_lab/database_jxzhang/Sequence_And_Annotation/01.Mus_musculus/01.mm10/01.genome/04.ENSEMBL/Mus_musculus.GRCm38.dna.toplevel.fa"
  mtGenome: "/public-supool/home/niehu/LFL_lab/database_jxzhang/Sequence_And_Annotation/01.Mus_musculus/01.mm10/01.genome/04.ENSEMBL/pacbio_index/Mus_musculus.mt.fa"
  clGenome: ""
  geneIndex: "/public-supool/home/niehu/LFL_lab/database_jxzhang/Sequence_And_Annotation/01.Mus_musculus/01.mm10/01.genome/04.ENSEMBL/pacbio_index/Mus_musculus.gene_idx/"

software:
  minimap2: "/public-supool/home/niehu/biosoft/minimap2/minimap2"
  featureCounts: "/public-supool/home/niehu/biosoft/bin/featureCounts"
  samtools: "/public-supool/home/niehu/LFL_lab/niehu/anaconda2/bin/samtools"
  bedtools: "/public-supool/home/niehu/LFL_lab/niehu/anaconda2/bin/bedtools"
  bowtie2-build: "/public-supool/home/niehu/biosoft/bowtie2-2.3.4.1-linux-x86_64/bowtie2-build"
  bowtie2: "/public-supool/home/niehu/biosoft/bowtie2-2.3.4.1-linux-x86_64/bowtie2"
  seqkit: "/public-supool/home/niehu/LFL_lab/niehu/anaconda2/bin/seqkit"
  blat: "/public-supool/home/niehu/biosoft/blat"
  nThreads: 20
